### ISSUE TITLE
Lack of naming convention for zg ?

### ISSUE THREAD

**Issue by mpmoine** [jonseddon/cmip6-cmor-tables#21]
Hi again,

This remark is not a purely Primavera-Tables issue, but is also valid for CMIP6 Tables ... 

It seems that there is a lack of naming convention/rules for `zg` variable. 

For instance :

- zg required on `plev27` is named `zg27` in tables CMIP6_6hrPlevPt, CMIP6_E1hr and CMIP6_Emon
- zg required on `plev8` is named `zg` (why not` zg8`?) in CMIP6_day
- zg required on `plev19` is named `zg` in table CMIP6_Amon and CMIP6_Eday, but named `zg19` in PRIMAVERA_Primday
- `zg10` means  "Geopotential Height at 10 hPa" (2D field) in CMIP6_AERday but `zg10` means  "Geopotential Height" on plev10 (3D field) in PRIMAVERA_Primday

I am aware there is still some ambiguities in the DR (variables having the same name but different cell_methods for instance), but in our case, we even use the same name for different spatial shapes (2D or 3D). 

It sounds confusing for the users and non standard that:
- sometimes the trailing number stands for the number of pressure levels, other times for the value of a single level in hPa
- sometimes the number of pressure levels is set as suffix, sometimes not.

What do you think?

Marie-Pierre.

**Comment by jonseddon** [comment]
Hi Marie-Pierre,

For the CMIP6 variables, you could flag these up at the CMIP6 data request Github site. However, I'm not sure how long any change will take to make it to a new release of the data request and if this fits with your timescales for starting model runs.

In Primday, zg10, zg19 and zg23 were added because they had been deleted from the CMIP6 Eday table. To maintain consistency, in Primday, the only one of these that looks as if it will be generated is zg23 by the Met Office. I would therefore propose that zg10 and zg19 are deleted from Primday.

This isn't an ideal solution, but will keep PRIMAVERA consistent with CMIP6 and we will have to see how CMIP6 evolves.

Thanks,

Jon

**Comment by mpmoine** [comment]
Hi again,

I agree with your "non-ideal" solution and will post an issue on DR github for the CMIP6 cases.

Regards,
Marie-Pierre.

**Comment by jonseddon** [comment]
Hi Marie-Pierre,

I have just updated the data request and files and zg10 and zg19 have been removed from Primday.

Thanks,

Jon
