### ISSUE TITLE
mrsls change to mrsol

### ISSUE THREAD

**Issue by oloapinivad** [jonseddon/cmip6-cmor-tables#46]
Variable **mrlsl** in Primday table correpond is:
 
````
   "mrlsl": {
            "frequency": "day",
            "modeling_realm": "land",
            "standard_name": "moisture_content_of_soil_layer",
            "units": "kg m-2",
            "cell_methods": "time: mean area: mean where land",
            "cell_measures": "area: areacella",
            "long_name": "Water Content of Soil Layer",
            "comment": "in each soil layer, the mass of water in all phases, including ice. Reported as \"\"missing\"\" for grid cells occupied entirely by \"\"sea\"\"",
            "dimensions": "longitude latitude sdepth time",
            "out_name": "mrlsl",
            "type": "real",
            "positive": "",
            "valid_min": "",
            "valid_max": "",
            "ok_min_mean_abs": "",
            "ok_max_mean_abs": "",
            "primavera_priority": "1"
        },
````

However, in CMIP6 tables this is called **mrsol**. I guess that the mrlsl name is deprecated.  See here from Emon table. 

`````
  "mrsol": {
            "frequency": "mon",
            "modeling_realm": "land",
            "standard_name": "moisture_content_of_soil_layer",
            "units": "kg m-2",
            "cell_methods": "area: mean where land time: mean",
            "cell_measures": "area: areacella",
            "long_name": "Total water content of soil layer",
            "comment": "in each soil layer, the mass of water in all phases, including ice.  Reported as 'missing' for grid cells occupied entirely by 'sea'",
            "dimensions": "longitude latitude sdepth time",
            "out_name": "mrsol",
            "type": "real",
            "positive": "",
            "valid_min": "",
            "valid_max": "",
            "ok_min_mean_abs": "",
            "ok_max_mean_abs": ""
        },
``````

This creates confusion when cmorizing PRIMAVERA data. 
Cheers,
Paolo

**Comment by jonseddon** [comment]
Hi Paolo,

We had to freeze the PRIMAVERA data request when groups began to produce data in May 2017. This has caused the PRIMAVERA data request to drift from the CMIP6 request in a small number of places. For a few diagnostics that are going to be submitted to the ESGF for CMIP6 we will have to edit their metadata to allow publication through ESGF. For the additional PRIMAVERA data that is not part of CMIP6 this is not required as we can publish any data that we want. Several groups have already produced mrlsl: https://prima-dm.ceda.ac.uk/received_data/?cmor_name=mrlsl. The difference in name between mrlsl and mrsol is not ideal but had to happen when groups started to produce data. The variable request allows users to search by standard_name to find data: https://prima-dm.ceda.ac.uk/variable_requests/?standard_name=moisture_content_of_soil_layer which will still identify mrlsl.

Is this change preventing you from producing this variable? If it is then we can come to an agreement so that you can still produce this variable. Otherwise, I'm afraid that the confusion is an unfortunate side-effect of PRIMAVERA being ahead of CMIP6. If you have any suggestions on how to improve the search on https://prima-dm.ceda.ac.uk/ so that users can identify these changes then please let me know and I can try to incorporate them.

Thanks,

Jon

**Comment by oloapinivad** [comment]
Hi Jon,

thank you for your reply. I totally understand the issue connected to the different time windows.

My concern is coming from the fact that using CMIP6 tables from the present archive I will produce **mrsol** while using PRIMAVERA tables will produce **mrlsl**. I am trying to cmorize PRIMAVERA data and I will have this inconsistency, producing the same variable at different time frequencies with different names. 

Would you recommend to use an older tag of the tables in this archive (in order to produce only mrlsl)? If this is the case, which version would be the best?

Thanks a lot
Paol

**Comment by jonseddon** [comment]
Hi Paol,

ESGF can only publish data from data request versions 01.00.13 and later. If you can use version 01.00.13 of the tables then you can use mrlsl for CMIP6 and PRIMAVERA.

However, this would have the disadvantage that the rest of the world searching for variable mrsol may not find your data for this variable (although if they searched by standard_name they would be fine). 

I'm afraid that there is no solution to this problem that satisfies every users' needs because of the previous changes in the CMIP6 data request. Please choose whatever option you consider will allow the most users to find your data.

Thanks,

Jon

PS I'm on annual leave from 12th to 21st May and won't have access to email/GitHub next week.

**Comment by oloapinivad** [comment]
Thanks Jon,
I will use version 01.00.13. 
Best,
Paolo
